### ISSUE TITLE
Package up as eslint-plugin for easier deployment

### ISSUE THREAD

**Issue by taybin** [bahmutov/eslint-rules#4]
Hi Gleb.

Can this get packaged up in the eslint-plugin-* format so it can be installed and automated via regular tooling?

**Comment by bahmutov** [comment]
I guess I can be, just never needed :)

How are you @taybin ?

**Comment by kentcdodds** [comment]
ping @bahmutov, I would love to use some of these rules :-)

**Comment by bahmutov** [comment]
maybe, if I get the time

**Comment by ericwooley** [comment]
bump, It shouldn't take much time, or I can fork and republish if you want

**Comment by bahmutov** [comment]
If you have time to do this, I would be very grateful and will merge quickly
